name: Linux CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y clang re2c
          python3 -m pip install uv
      - name: Build
        run: ./build.sh
      - name: Run tests
        run: uv run run_tests.py
